services:
#    blogger_blog.example:
#        class: Blogger\BlogBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  Blogger\BlogBundle\DataFixtures\ORM\BlogFixtures:
    tags: [doctrine.fixture.orm]
  Blogger\BlogBundle\DataFixtures\ORM\CommentFixtures:
    tags: [doctrine.fixture.orm]
    